routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('page/index');
});

Route::prefix('ajax')->namespace('Ajax')->group(function() {
    Route::get('event/callingEvents', 'EventController@callingEvents');
    Route::get('event/presentation', 'EventController@presentation');
});

Route::prefix('admin')->namespace('Admin')->group(function() {
    Route::get('/', function () {
        return view('admin.index');
    });

    Route::get('event/clearPresentation', 'EventController@clearPresentation')
        ->name('event.clearPresentation');
    
    Route::resource('event', 'EventController');
    Route::get('event/{event}/call', 'EventController@callEvent')
        ->name('event.call');
    Route::get('event/{event}/uncall', 'EventController@uncallEvent')
        ->name('event.uncall');
    Route::post('event/{event}/updateRank', 'EventController@updateRank')
        ->name('event.updateRank');

    Route::get('event/{event}/presenting', 'EventController@presenting')
        ->name('event.presenting');

    /* UNUSED */
    Route::post('event/{event}/addCompetitor', 'EventController@addCompetitor')
        ->name('event.addCompetitor');
    Route::get('event/{event}/removeCompetitor/{competitor}', 'EventController@removeCompetitor')
        ->name('event.removeCompetitor');

    Route::resource('competitor', 'CompetitorController');
    
});

Route::get('results', 'ResultController@index')
    ->name('result');
Route::get('results/event/{event}', 'ResultController@event')
    ->name('result.event');

// Catch all
Route::get('/{page}', function ($page) {
    $page = str_replace('-', '_', $page);
    return view("page.{$page}");
});

app/Models/Competitor.php
<?php

namespace App\Models;

use App\Models\Model;

class Competitor extends Model {
    
    /**
     * Event participant relationships.
     */
    public function events()
    {
        return $this->belongsToMany('App\Models\Event')->withPivot('rank');
    }

}

app/Http/Controllers/Admin/CompetitorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Competition\Competition;
use App\Http\Controllers\Controller;
use App\Models\Competitor;
use App\Models\Event;
use Request;

class CompetitorController extends Controller {

    /**
     * Searchable, listing of competitors.
     */
    public function index()
    {
        $competitors = Competitor::orderBy('name', 'asc')
            ->orderBy('num', 'asc')
            ->paginate();

        return view('admin.competitor.index', compact('competitors'));
    }


    public function create()
    {
        return view('admin.competitor.create');
    }

    public function store(Request $request)
    {
        $competitor = new Competitor([
            'name' => $request->name,
            'num' => $request->num,
        ]);

        $competitor->save();
        return redirect()->route('competitor.show', $competitor);
    }

    public function show(Competitor $competitor)
    {
        $events = $competitor->events()->orderBy('num', 'asc')->get();
        return view('admin.competitor.show', compact('competitor', 'events'));
    }

    public function edit(Request $request, Competitor $competitor)
    {

    }

    public function destroy(Competitor $competitor)
    {

    }

}

resources/views/admin/competitor/create.blade.php
@extends('layouts.app')

@section('title', 'New Competitor')

@section('content')
    <h1>New Competitor</h1>

    <div class="row">
        <div class="col-6">
            {{ Form::open(['route' => ['competitor.store']]) }}

                <div class="form-group">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', null, ['class' => 'form-control']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('num', 'Tag Number') }}
                    {{ Form::text('num', null, ['class' => 'form-control']) }}
                    <small class="form-text text-muted">Leave this blank if you want system to auto-generate tag number.</small>
                </div>

                {{ Form::submit('Save', ['class' => 'btn btn-primary']) }}

            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/admin/competitor/index.blade.php
@extends('layouts.app')

@section('title', 'Competitors')

@section('content')
    <h1>Competitors</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Number</th>
                <th>Name</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($competitors as $competitor)
                <tr>
                    <td>{{ $competitor->num }}</td>
                    <td>{{ link_to_route('competitor.show', $competitor->name, [$competitor]) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $competitors->links() }}
@endsection

resources/views/admin/competitor/show.blade.php
@extends('layouts.app')

@section('title', $competitor->name)

@section('content')
    <h1>{{ $competitor->name }}</h1>

    <h2>Events</h2>

    @foreach ($events as $event)
        <h4>{{ link_to_route('event.show', "{$event->num}. {$event->name}", [$event]) }}</h4>
    @endforeach
    
@endsection